### ISSUE TITLE
Separated exit head

### ISSUE THREAD

**Issue by dustinlacewell** [jerrypnz/major-mode-hydra.el#14]
A nice feature would be being able to specify an exit head independent from any column and having it show under the Hydra. This would probably just look a little nicer than having to stick an exit head on a column.

**Comment by jerrypnz** [comment]
I recently implemented this on `develop` branch which seems close to what you want:
https://github.com/jerrypnz/major-mode-hydra.el/tree/develop#add-an-invisible-hydra-head-for-quitting

You can't assign different exit keys for different hydras and the exit head is not visible, which isn't a problem for myself because I just stick to `q` and don't really need it displayed.
